version: '3.8'

services:
  db:
    image: postgres
    container_name: ChallengeDB
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - bossaChallenge

  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - bossaChallenge

networks:
  bossaChallenge:
    driver: bridge
